#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
GROUP=io.github.linreal
POM_ARTIFACT_ID=cascade-editor
VERSION_NAME=1.8.1

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
